version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "1111:1111"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always